import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import TestCard from '../../components/TestCard/TestCard'
import PackageCard from '../../components/PackageCard/PackageCard'
import { getTests } from '../../services/testService'
import { getPackages } from '../../services/packageService'
import { getCustomerCoupons } from '../../services/couponService'
import { whatsappLink } from '../../config/business'
import { getSelectedCity, isServiceableCity, setSelectedCity, SUPPORTED_CITIES } from '../../config/serviceability'
import { useCart } from '../../context/CartContext'
import { money } from '../../utils/catalogue'
import './Home.css'

function SearchResult({ item, type }) {
  const { add } = useCart(); const navigate = useNavigate()
  const book = () => { add({ ...item, type, reference:item._id, price:item.sellingPrice }); navigate('/book') }
  return <article className="home-search-result"><Link to={type === 'TEST' ? `/tests/${item.slug}` : `/packages/${item.slug}`}><b>{item.name}</b><span>{money(item.sellingPrice)} · {item.reportTAT || 'Home collection'}</span></Link><button className="button button-primary" onClick={book}>Book</button></article>
}

export default function Home() {
  const [tests, setTests] = useState([]), [packages, setPackages] = useState([]), [offers, setOffers] = useState([])
  const [search, setSearch] = useState(''), [city, setCity] = useState(getSelectedCity), [error, setError] = useState(''), [detectingLocation, setDetectingLocation] = useState(false), [slide, setSlide] = useState(0)
  useEffect(() => { document.title = 'Diagnostic Tests & Home Collection in Indore & Bhopal | LabNivo' }, [])
  useEffect(() => { if (city || !navigator.geolocation) return; setDetectingLocation(true); navigator.geolocation.getCurrentPosition(async position => { try { const response = await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&zoom=10&lat=${position.coords.latitude}&lon=${position.coords.longitude}`); const result = await response.json(); const detected = result?.address?.city || result?.address?.town || result?.address?.county; if (isServiceableCity(detected)) { const supported = SUPPORTED_CITIES.find(item => item.toLowerCase() === detected.toLowerCase()); setCity(supported); setSelectedCity(supported) } } catch {} finally { setDetectingLocation(false) } }, () => setDetectingLocation(false), { enableHighAccuracy:false, timeout:8000, maximumAge:300000 }) }, [city])
  useEffect(() => { Promise.all([getTests({ status:'active' }), getPackages(), getCustomerCoupons().catch(() => [])]).then(([testData, packageData, couponData]) => { setTests(testData); setPackages(packageData); setOffers(couponData) }).catch(() => setError('Unable to load catalogue highlights. Please try again.')) }, [])
  useEffect(() => { const timer = window.setInterval(() => setSlide(current => (current + 1) % 3), 4500); return () => window.clearInterval(timer) }, [])
  const matches = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return []; const testMatches = tests.filter(item => `${item.name} ${item.category} ${item.shortDescription}`.toLowerCase().includes(query)).slice(0, 4).map(item => ({ item, type:'TEST' })); const packageMatches = packages.filter(item => `${item.name} ${item.description}`.toLowerCase().includes(query)).slice(0, 3).map(item => ({ item, type:'PACKAGE' })); return [...testMatches, ...packageMatches].slice(0, 6) }, [search, tests, packages])
  const popularTests = tests.filter(item => /cbc|hba1c|thyroid|vitamin d|liver|kidney/i.test(item.name)).slice(0, 4)
  const carousel = [offers[0] ? { eyebrow:'LIMITED TIME OFFER', title:`Get ${offers[0].discountType === 'PERCENTAGE' ? `${offers[0].discountValue}%` : money(offers[0].discountValue)} OFF`, text:'Selected tests and packages', link:'/tests', cta:'Book Now →' } : { eyebrow:'HEALTH CHECKS', title:'Care that starts with clarity', text:'Explore tests and packages for your needs.', link:'/tests', cta:'Explore →' }, { eyebrow:'HOME SAMPLE COLLECTION', title:'Tests at your doorstep', text:'Convenient sample collection where available.', link:'/tests', cta:'Book Test →' }, { eyebrow:'HAVE A PRESCRIPTION?', title:"Upload & we'll help you", text:'Share your prescription and our team will assist.', link:'/upload-prescription', cta:'Upload Now →' }]
  const selectCity = event => { setCity(event.target.value); setSelectedCity(event.target.value) }
  return <main className="home-page">
    <section className="lab-hero"><div className="lab-hero-copy"><span className="hero-brand">LAB NIVO</span><label className="hero-location"><span>📍</span>{detectingLocation ? 'Detecting your location...' : 'Delivering in'}<select value={city} onChange={selectCity} aria-label="Select service city"><option value="">Select City</option>{SUPPORTED_CITIES.map(item => <option key={item}>{item}</option>)}</select></label><h1>Accurate Tests.<br/><em>A Healthier Tomorrow.</em></h1><p>Book trusted diagnostic tests and convenient home sample collection.</p><div className="hero-search"><span>⌕</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search tests, packages or health concerns..." aria-label="Search tests and packages"/></div>{search && <section className="home-search-results" aria-live="polite">{matches.length ? matches.map(({ item, type }) => <SearchResult key={`${type}-${item._id}`} item={item} type={type}/>) : <p>No matching tests or packages. <Link to="/tests">Browse all tests</Link></p>}</section>}<div className="hero-actions"><Link className="button button-primary" to="/tests">Explore Tests →</Link><Link className="button button-secondary" to="/upload-prescription">Upload Prescription</Link></div></div><div className="lab-hero-art" aria-label="Laboratory diagnostic equipment illustration"><div className="lab-orbit"/><div className="microscope"><i/><b/><strong/><span/></div><div className="tube tube-one"/><div className="tube tube-two"/><div className="hero-lab-card">✦ <span>Home collection<small>Simple. Convenient.</small></span></div></div></section>
    <section className="offer-carousel" aria-label="LAB NIVO offers"><div className="offer-track" style={{ transform:`translateX(-${slide * 100}%)` }}>{carousel.map((item, index) => <article className={`offer-slide offer-${index}`} key={item.title}><span>{item.eyebrow}</span><h2>{item.title}</h2><p>{item.text}</p><Link to={item.link}>{item.cta}</Link></article>)}</div><div className="offer-dots">{carousel.map((item, index) => <button type="button" key={item.title} className={slide === index ? 'active' : ''} aria-label={`Show offer ${index + 1}`} onClick={() => setSlide(index)}/>)}</div></section>
    <section className="benefit-grid">{[['⌂','Home Sample Collection'],['✓','Reliable Reports'],['₹','Transparent Pricing'],['↗','Easy Booking'],['◉','WhatsApp Support']].map(([icon, label]) => <article key={label}><i>{icon}</i><span>{label}</span></article>)}</section>
    <section className="home-section package-showcase"><div className="home-heading"><div><span>POPULAR HEALTH PACKAGES</span><h2>Health checks made simple</h2></div><Link to="/packages">View all →</Link></div>{error ? <p className="form-error">{error}</p> : <div className="package-grid">{packages.slice(0, 3).map(item => <PackageCard key={item.slug} pack={item}/>)}</div>}</section>
    <section className="home-section test-showcase"><div className="home-heading"><div><span>POPULAR DIAGNOSTIC TESTS</span><h2>Start with what matters</h2></div><Link to="/tests">View all →</Link></div><div className="test-grid">{(popularTests.length ? popularTests : tests.slice(0, 4)).map(item => <TestCard key={item.slug} test={item}/>)}</div></section>
    <section className="how-it-works"><span>HOW IT WORKS</span><h2>Diagnostics in four simple steps</h2><div>{[['01','Choose Test'],['02','Book Appointment'],['03','Home Sample Collection'],['04','Get Report']].map(([number, label]) => <article key={number}><b>{number}</b><p>{label}</p></article>)}</div></section>
    <section className="home-cta"><div><span>DOCTOR'S PRESCRIPTION</span><h2>Need help choosing tests?</h2><p>Upload a prescription or speak to our team on WhatsApp.</p></div><div><Link className="button button-primary" to="/upload-prescription">Upload Prescription</Link><a className="button button-secondary" href={whatsappLink('Hello LAB NIVO, I would like help booking a diagnostic test.')} target="_blank" rel="noreferrer">WhatsApp Us</a></div></section>
    <footer className="contact-section"><h2>LAB NIVO</h2><p>Diagnostics at Your Doorstep</p><p><Link to="/tests">Tests</Link> · <Link to="/packages">Packages</Link> · <Link to="/my-orders">My Orders</Link> · <Link to="/contact">Need Help</Link></p></footer>
  </main>
}
