import Test from '../models/Test.js'
import Package from '../models/Package.js'

const slugify = value => String(value || '').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const discount = (mrp, sellingPrice) => mrp ? Number((((mrp - sellingPrice) / mrp) * 100).toFixed(2)) : 0
function prices(input) { const mrp = Number(input.mrp); const sellingPrice = Number(input.sellingPrice); if (!Number.isFinite(mrp) || mrp < 0 || !Number.isFinite(sellingPrice) || sellingPrice < 0 || sellingPrice > mrp) throw new Error('Selling Price cannot exceed MRP.'); return { mrp, sellingPrice, discountPercent: discount(mrp, sellingPrice) } }
function testValues(body) { const price = prices(body); return { name: String(body.name || '').trim(), slug: slugify(body.slug || body.name), category: String(body.category || '').trim(), shortDescription: String(body.description ?? body.shortDescription ?? '').trim(), sampleType: String(body.sampleType || '').trim(), preparation: String(body.preparation ?? body.preparationInstructions ?? '').trim(), reportTAT: String(body.reportTAT ?? body.tat ?? '').trim(), imageUrl: String(body.imageUrl || '').trim(), homeCollection: body.homeCollection !== false, fastingRequired: Boolean(body.fastingRequired), status: body.active === false || body.status === 'inactive' ? 'inactive' : 'active', ...price } }
function packageValues(body) { const price = prices(body); return { name: String(body.name || '').trim(), slug: slugify(body.slug || body.name), description: String(body.description || '').trim(), includedTests: Array.isArray(body.includedTests ?? body.tests) ? body.includedTests ?? body.tests : [], imageUrl: String(body.imageUrl || '').trim(), preparation: String(body.preparation || 'Follow collection instructions shared before collection.').trim(), reportTAT: String(body.reportTAT ?? body.tat ?? '24–48 hours').trim(), status: body.active === false || body.status === 'inactive' ? 'inactive' : 'active', ...price } }
function validationError(error, response) { return response.status(400).json({ success: false, message: error.message || 'Enter valid catalogue values.' }) }

export async function listAdminTests(_request, response, next) { try { response.json({ success: true, data: await Test.find().sort({ category: 1, name: 1 }) }) } catch (error) { next(error) } }
export async function createAdminTest(request, response, next) { try { const value = testValues(request.body); if (!value.name || !value.slug || !value.category || !value.shortDescription || !value.sampleType || !value.preparation || !value.reportTAT) throw new Error('Complete all required test fields.'); const data = await Test.create({ ...value, partnerLabCost: Math.max(0, Number(request.body.partnerLabCost || 0)), collectionCost: Math.max(0, Number(request.body.collectionCost || 0)) }); response.status(201).json({ success: true, data }) } catch (error) { if (error.message || error.name === 'ValidationError') return validationError(error, response); next(error) } }
export async function updateAdminTest(request, response, next) { try { const value = testValues(request.body); const data = await Test.findByIdAndUpdate(request.params.id, value, { new: true, runValidators: true }); if (!data) return response.status(404).json({ success: false, message: 'Test not found.' }); response.json({ success: true, data }) } catch (error) { if (error.message || error.name === 'ValidationError') return validationError(error, response); next(error) } }
export async function toggleAdminTest(request, response, next) { try { const data = await Test.findByIdAndUpdate(request.params.id, { status: request.body.active === false ? 'inactive' : 'active' }, { new: true }); if (!data) return response.status(404).json({ success: false, message: 'Test not found.' }); response.json({ success: true, data }) } catch (error) { next(error) } }
export async function listAdminPackages(_request, response, next) { try { response.json({ success: true, data: await Package.find().populate('includedTests', 'name status').sort({ name: 1 }) }) } catch (error) { next(error) } }
export async function createAdminPackage(request, response, next) { try { const value = packageValues(request.body); if (!value.name || !value.slug || !value.description || !value.includedTests.length) throw new Error('Complete all required package fields and select at least one test.'); const count = await Test.countDocuments({ _id: { $in: value.includedTests } }); if (count !== value.includedTests.length) throw new Error('One or more selected tests do not exist.'); const data = await Package.create(value); response.status(201).json({ success: true, data }) } catch (error) { if (error.message || error.name === 'ValidationError') return validationError(error, response); next(error) } }
export async function updateAdminPackage(request, response, next) { try { const value = packageValues(request.body); if (!value.includedTests.length) throw new Error('Select at least one test.'); const count = await Test.countDocuments({ _id: { $in: value.includedTests } }); if (count !== value.includedTests.length) throw new Error('One or more selected tests do not exist.'); const data = await Package.findByIdAndUpdate(request.params.id, value, { new: true, runValidators: true }); if (!data) return response.status(404).json({ success: false, message: 'Package not found.' }); response.json({ success: true, data }) } catch (error) { if (error.message || error.name === 'ValidationError') return validationError(error, response); next(error) } }
export async function toggleAdminPackage(request, response, next) { try { const data = await Package.findByIdAndUpdate(request.params.id, { status: request.body.active === false ? 'inactive' : 'active' }, { new: true }); if (!data) return response.status(404).json({ success: false, message: 'Package not found.' }); response.json({ success: true, data }) } catch (error) { next(error) } }
