import crypto from 'crypto'
import fs from 'fs'
import path from 'path'
import mongoose from 'mongoose'
import multer from 'multer'
import PrescriptionLead,{PRESCRIPTION_STATUSES} from '../models/PrescriptionLead.js'
const uploadDir=path.resolve('uploads/prescriptions');fs.mkdirSync(uploadDir,{recursive:true})
const allowed=new Set(['image/jpeg','image/jpg','image/png','application/pdf']);const extension={ 'image/jpeg':'.jpg','image/jpg':'.jpg','image/png':'.png','application/pdf':'.pdf'}
const storage=multer.diskStorage({destination:uploadDir,filename:(_r,file,done)=>done(null,`prescription-${crypto.randomUUID()}${extension[file.mimetype]||''}`)})
export const prescriptionUpload=multer({storage,limits:{fileSize:5*1024*1024},fileFilter:(_r,file,done)=>done(null,allowed.has(file.mimetype))}).single('prescription')
const fields=['patientName','mobile','alternateMobile','age','gender','address','village','area','city','district','state','pincode','landmark','preferredCallbackTime','notes']
function data(input){return Object.fromEntries(fields.map(key=>[key,typeof input[key]==='string'?input[key].trim():input[key]]))}
async function nextId(){const result=await mongoose.connection.collection('counters').findOneAndUpdate({_id:'prescriptionLeadId'},[{$set:{sequence:{$add:[{$ifNull:['$sequence',10000]},1]}}}],{upsert:true,returnDocument:'after'});return `LN-P-${result?.value?.sequence??result.sequence}`}
export async function createPrescription(request,response,next){try{const item=data(request.body);if(!request.file)return response.status(400).json({success:false,message:'Please attach a JPG, PNG, or PDF prescription under 5 MB.'});const invalid=!item.patientName||!/^\d{10}$/.test(item.mobile||'')||!item.address||!item.city||!/^\d{6}$/.test(item.pincode||'')||(item.age&&(!Number.isInteger(Number(item.age))||Number(item.age)<1||Number(item.age)>120))||(item.gender&&!['male','female','other'].includes(item.gender));if(invalid){fs.unlink(request.file.path,()=>{});return response.status(400).json({success:false,message:'Please fill all required details correctly.'})}if(item.alternateMobile&&!/^\d{10}$/.test(item.alternateMobile)){fs.unlink(request.file.path,()=>{});return response.status(400).json({success:false,message:'Enter a valid alternate mobile number.'})}const lead=await PrescriptionLead.create({...item,leadId:await nextId(),prescriptionFileName:request.file.filename,prescriptionOriginalName:request.file.originalname,prescriptionMimeType:request.file.mimetype,prescriptionFilePath:request.file.filename,prescriptionFileSize:request.file.size});response.status(201).json({success:true,data:{leadId:lead.leadId}})}catch(error){next(error)}}
export async function viewPrescriptionFile(request,response,next){try{const lead=await PrescriptionLead.findOne({leadId:request.params.leadId.toUpperCase()});if(!lead)return response.status(404).json({success:false,message:'Lead not found'});const safe=path.basename(lead.prescriptionFilePath);const file=path.join(uploadDir,safe);if(!fs.existsSync(file))return response.status(404).json({success:false,message:'Prescription file not found'});response.type(lead.prescriptionMimeType);response.sendFile(file)}catch(error){next(error)}}
export async function listPrescriptionLeads(_r,response,next){try{response.json({success:true,data:await PrescriptionLead.find().sort({createdAt:-1})})}catch(error){next(error)}}
export async function getPrescriptionLead(request,response,next){try{const data=await PrescriptionLead.findOne({leadId:request.params.leadId.toUpperCase()});if(!data)return response.status(404).json({success:false,message:'Lead not found'});response.json({success:true,data})}catch(error){next(error)}}
export async function updatePrescriptionStatus(request,response,next){try{if(!PRESCRIPTION_STATUSES.includes(request.body.status))return response.status(400).json({success:false,message:'Invalid lead status.'});const data=await PrescriptionLead.findOneAndUpdate({leadId:request.params.leadId.toUpperCase()},{status:request.body.status},{new:true});if(!data)return response.status(404).json({success:false,message:'Lead not found'});response.json({success:true,data})}catch(error){next(error)}}
