import mongoose from 'mongoose'
import Quotation, { QUOTATION_STATUSES } from '../models/Quotation.js'
import PrescriptionLead from '../models/PrescriptionLead.js'
import Test from '../models/Test.js'
import Customer from '../models/Customer.js'
import Booking from '../models/Booking.js'

async function nextQuotationId() { const result = await mongoose.connection.collection('counters').findOneAndUpdate({ _id: 'quotationId' }, [{ $set: { sequence: { $add: [{ $ifNull: ['$sequence', 10000] }, 1] } } }], { upsert: true, returnDocument: 'after' }); return `LN-Q-${result?.value?.sequence ?? result.sequence}` }
async function nextBookingId() { const result = await mongoose.connection.collection('counters').findOneAndUpdate({ _id: 'bookingId' }, [{ $set: { sequence: { $add: [{ $ifNull: ['$sequence', 10000] }, 1] } } }], { upsert: true, returnDocument: 'after' }); return `LN-B-${result?.value?.sequence ?? result.sequence}` }
const customerSafe = quotation => ({ quotationId: quotation.quotationId, selectedTests: quotation.selectedTests.map(({ name, quantity, sellingPrice }) => ({ name, quantity, sellingPrice })), subtotal: quotation.subtotal, discount: quotation.discount, collectionCharge: quotation.collectionCharge, finalAmount: quotation.finalAmount, status: quotation.status, createdAt: quotation.createdAt })
export async function createQuotation(request, response, next) { try { const lead = await PrescriptionLead.findOne({ leadId: request.params.leadId.toUpperCase() }); const ids = [...new Set((request.body.tests || []).map(item => String(item.testId)).filter(mongoose.isValidObjectId))]; if (!lead) return response.status(404).json({ success: false, message: 'Lead not found.' }); if (!ids.length) return response.status(400).json({ success: false, message: 'Select at least one test.' }); const tests = await Test.find({ _id: { $in: ids }, status: 'active' }); if (tests.length !== ids.length) return response.status(400).json({ success: false, message: 'One or more selected tests are unavailable.' }); const quantities = new Map((request.body.tests || []).map(item => [String(item.testId), Math.max(1, Math.floor(Number(item.quantity) || 1))])); const selectedTests = tests.map(test => ({ test: test._id, name: test.name, quantity: quantities.get(String(test._id)), mrp: test.mrp, discountPercent: test.discountPercent, sellingPrice: test.sellingPrice })); const subtotal = selectedTests.reduce((sum, item) => sum + item.mrp * item.quantity, 0); const finalAmount = selectedTests.reduce((sum, item) => sum + item.sellingPrice * item.quantity, 0); const collectionCharge = Math.max(0, Number(process.env.COLLECTION_CHARGE ?? 0)); const quotation = await Quotation.create({ quotationId: await nextQuotationId(), lead: lead._id, selectedTests, subtotal, discount: subtotal - finalAmount, collectionCharge, finalAmount: finalAmount + collectionCharge }); response.status(201).json({ success: true, data: quotation }) } catch (error) { next(error) } }
export async function getAdminQuotationForLead(request, response, next) { try { const lead = await PrescriptionLead.findOne({ leadId: request.params.leadId.toUpperCase() }); if (!lead) return response.status(404).json({ success: false, message: 'Lead not found.' }); const data = await Quotation.find({ lead: lead._id }).sort({ createdAt: -1 }); response.json({ success: true, data }) } catch (error) { next(error) } }
export async function getCustomerQuotation(request, response, next) { try { const quotation = await Quotation.findOne({ quotationId: request.params.quotationId.toUpperCase() }).populate('lead'); if (!quotation || quotation.lead.mobile !== request.customerMobile) return response.status(404).json({ success: false, message: 'Quotation not found.' }); response.json({ success: true, data: customerSafe(quotation) }) } catch (error) { next(error) } }
export async function approveQuotation(request, response, next) { try { const quotation = await Quotation.findOne({ quotationId: request.params.quotationId.toUpperCase() }).populate('lead'); if (!quotation || quotation.lead.mobile !== request.customerMobile) return response.status(404).json({ success: false, message: 'Quotation not found.' }); if (quotation.status !== 'CREATED') return response.status(400).json({ success: false, message: 'This quotation cannot be approved.' }); quotation.status = 'CUSTOMER_APPROVED'; await quotation.save(); response.json({ success: true, data: customerSafe(quotation) }) } catch (error) { next(error) } }
export async function setQuotationStatus(request, response, next) { try { if (!['CUSTOMER_APPROVED', 'CUSTOMER_REJECTED', 'EXPIRED'].includes(request.body.status)) return response.status(400).json({ success: false, message: 'Invalid quotation status.' }); const quotation = await Quotation.findOneAndUpdate({ quotationId: request.params.quotationId.toUpperCase(), status: { $in: ['CREATED', 'CUSTOMER_APPROVED'] } }, { status: request.body.status }, { new: true }); if (!quotation) return response.status(404).json({ success: false, message: 'Quotation not found or cannot be changed.' }); response.json({ success: true, data: quotation }) } catch (error) { next(error) } }
export async function convertQuotation(request, response, next) { try { const quotation = await Quotation.findOne({ quotationId: request.params.quotationId.toUpperCase() }).populate('lead'); if (!quotation) return response.status(404).json({ success: false, message: 'Quotation not found.' }); if (quotation.status !== 'CUSTOMER_APPROVED') return response.status(400).json({ success: false, message: 'Customer approval is required before conversion.' }); const lead = quotation.lead; const customer = await Customer.create({ name: lead.patientName, mobile: lead.mobile, alternateMobile: lead.alternateMobile, age: lead.age, gender: lead.gender, address: lead.address, village: lead.village, area: lead.area, city: lead.city, district: lead.district, state: lead.state, pincode: lead.pincode, landmark: lead.landmark }); const booking = await Booking.create({ bookingId: await nextBookingId(), customer: customer._id, items: quotation.selectedTests.map(item => ({ type: 'TEST', typeModel: 'Test', reference: item.test, name: item.name, quantity: item.quantity, mrp: item.mrp, discountPercent: item.discountPercent, sellingPrice: item.sellingPrice })), totalMRP: quotation.subtotal, totalDiscount: quotation.discount, subtotal: quotation.finalAmount - quotation.collectionCharge, couponCode: '', discountAmount: 0, totalAmount: quotation.finalAmount, collectionCharge: quotation.collectionCharge, address: [lead.address, lead.village, lead.area, lead.city, lead.district, lead.state, lead.pincode].filter(Boolean).join(', '), preferredDate: new Date(), preferredTimeSlot: '9:00 AM - 11:00 AM', notes: lead.notes, quotationId: quotation.quotationId, prescriptionLeadId: lead.leadId, paymentMethod: 'PAY_AT_COLLECTION', paymentStatus: 'PENDING' }); quotation.status = 'CONVERTED_TO_BOOKING'; quotation.booking = booking._id; await quotation.save(); lead.status = 'CONVERTED_TO_BOOKING'; await lead.save(); response.status(201).json({ success: true, data: { bookingId: booking.bookingId } }) } catch (error) { next(error) } }
export { QUOTATION_STATUSES }
