import { Link } from 'react-router-dom'
import { BUSINESS_EMAIL, BUSINESS_PHONE_NUMBER, whatsappLink } from '../../config/business'
import './Info.css'

const faqs = ['How does LAB NIVO work?', 'How does home collection work?', 'Who processes my sample?', 'How do I receive my report?', 'How can I cancel my booking?', 'How can I contact support?']
export function Contact() {
  return <main className="info-page"><span className="overline">CONTACT LAB NIVO</span><h1>We’re Here to Help</h1><p className="info-lead">Our team can help with booking, serviceability, prescriptions and existing bookings.</p><section className="contact-cards"><a href={whatsappLink('Hello LAB NIVO, I need help.')} target="_blank" rel="noreferrer"><b>WhatsApp</b><span>Chat on WhatsApp</span></a><a href={`tel:${BUSINESS_PHONE_NUMBER}`}><b>Call Us</b><span>+91 7987659405</span></a><a href={`mailto:${BUSINESS_EMAIL}`}><b>Email</b><span>{BUSINESS_EMAIL}</span></a></section><section className="info-panel"><h2>Send us a message</h2><form className="booking-form" onSubmit={event => event.preventDefault()}><div className="form-grid"><label>Name<input required /></label><label>Mobile<input required inputMode="numeric" /></label><label>Email<input type="email" /></label><label>Query type<select><option>Booking help</option><option>Serviceability</option><option>Report / booking</option><option>Other</option></select></label><label className="wide">Message<textarea required /></label></div><a className="button button-primary" href={whatsappLink('Hello LAB NIVO, I would like support with: ')}>Continue on WhatsApp</a></form></section><section className="info-panel"><h2>Service locations</h2><p>Currently serving Indore and Bhopal. Home sample collection is arranged where available.</p></section><section className="info-panel"><h2>Frequently asked questions</h2>{faqs.map(question => <details key={question}><summary>{question}</summary><p>{question.includes('processes') ? 'LAB NIVO is a diagnostic booking platform. Samples are processed by the applicable partner diagnostic laboratory.' : 'Please contact our support team for help with your booking and the available process.'}</p></details>)}</section></main>
}
export function PartnerNetwork() {
  return <main className="info-page"><span className="overline">TRANSPARENCY</span><h1>Quality Diagnostics, Together</h1><p className="info-lead">LAB NIVO is a diagnostic booking platform that connects customers with applicable partner diagnostic laboratories.</p><section className="info-panel"><h2>How the process works</h2><ol><li>Customer books through LAB NIVO.</li><li>Collection is arranged where available.</li><li>The sample is handled by the applicable partner diagnostic laboratory.</li><li>Testing and processing are performed through the available process.</li><li>The report is delivered through the available process.</li></ol><Link className="button button-primary" to="/tests">Explore diagnostic tests</Link></section><section className="info-panel"><h2>Clear, responsible information</h2><p>We do not represent LAB NIVO as owning a pathology laboratory. Availability, collection and reporting can vary by location and booking.</p></section></main>
}
export function HowItWorks() { return <main className="info-page"><span className="overline">HOW IT WORKS</span><h1>Simple diagnostic booking</h1><section className="info-panel"><ol><li>Search and choose a test or health package.</li><li>Book online with your collection details.</li><li>Sample collection is arranged where available.</li><li>Processing takes place at the applicable partner laboratory.</li><li>Get your report through the available process.</li></ol><Link className="button button-primary" to="/tests">Book a Test</Link></section></main> }
